#' The snv_count function takes as input the vector of SNVs generated by the snv_extraction function (or
#' a vector with an equivalent structure) and counts the number of snv_vector. It also provides the percentage
#' value of that mutation.
#'
#' @param snv_vector a vector of SNVs like the one returned by snv_extraction
#' @examples
#' library(BSgenome.Hsapiens.UCSC.hg38)
#' library(VariantAnnotation)
#' genome_ref <- BSgenome.Hsapiens.UCSC.hg38
#' path_to_vcf <- system.file("extdata", "chr22.vcf.gz", package="VariantAnnotation")
#' vcf <- readVcf(path_to_vcf, "hg38")
#' vector_snv <- snv_extraction(vcf, 5, genome_ref)
#' snv_table <- snv_count(vector_snv)
#' @usage snv_table <- snv_count(vector_snv)
#'
#'
#' @export


snv_count <- function(snv_vector) {

  #check if all elements in the vector match the pattern
  if (!all(grepl("\\[.*\\]", snv_vector))) {
    stop("The vector must have the same structure of the vectors returned by snv_extraction")
  }

  #extract the snv type from each string
  mut_types <- vector("character", length(snv_vector))
  for (i in seq_along(snv_vector)) {
    mut_types[i] <- gsub(".*\\[(.*)\\].*", "\\1", snv_vector[i])
  }

  #count the frequency
  count <- table(mut_types)

  #also calculate the percentage in which each mutation occours over the total number in the vector
  total_snv_vector <- sum(count)
  percentages <- round((count / total_snv_vector) * 100)

  #create the data frame
  table <- as.data.frame(count, stringsAsFactors = FALSE)
  colnames(table) <- c("SNV", "Count")

  #add the percentage column
  table$Percentage <- percentages

  #convert the columns that aren't numeric to numeric
  table$Count <- as.numeric(table$Count)
  table$Percentage <- as.numeric(table$Percentage)

  return(table)
}
